branch-defaults:
  default:
    environment: api-udagram-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: api-udagram
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  #profile: null
  repository: null
  sc: null
  workspace_type: Application